apiVersion: v1
kind: Service
metadata:
  name: {{ include "ddai-ms-merchant.fullname" . }}
  labels:
    app: {{ include "ddai-ms-merchant.name" . }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: {{ include "ddai-ms-merchant.name" . }}
